export const state = {
  hardwareType: 'Bolt',
  systemType: 'Metric',
  fuseType: 'Glass',
  switchType: '',
  threadSize: '',
  length: '',
  fuseValue: '',
  glassSpeed: '',
  glassSize: '',
  notes: '',
  standard: '',
  standardCode: '',
  boltHead: '',
  boltDrive: '',
  nutType: '',
  washerType: '',
  showText: true,
  showTextMain: true,
  showTextInfo: true,
  showTextInfoLine2: true,
  showTextInfoLine3: true,
  showImage: true,
  showQr: false,
  qrContent: '',
  widthMm: 37,
  heightMm: 12,
  connectorCategory: '',
  componentCategory: 'Resistor',
  componentMount: 'Through-Hole',
  resistorValue: '',
  capacitorValue: '',
  diodeValue: '',
  mosfetChannel: '',
  mosfetPart: '',
  potentiometerValue: '',
  potentiometerTaper: '',
  bearingType: '',
  bearingDetails: '',
  customLine1: '',
  customLine2: '',
  customGraphicSource: 'image',
  customIconStyle: 'solid',
  customIconName: '',
  customIconUnicode: '',
  customIconLabel: '',
  customIconSvgData: '',
  customImageData: '',
  customImageName: '',
  customPartId: '',
};

export const standardFilterState = {
  query: '',
};
