export const state = {
  hardwareType: 'Bolt',
  systemType: 'Metric',
  fuseType: 'Glass',
  threadSize: '',
  length: '',
  fuseValue: '',
  glassSpeed: '',
  glassSize: '',
  ceramicSpeed: '',
  ceramicSize: '',
  notes: '',
  standard: '',
  standardCode: '',
  boltHead: '',
  boltDrive: '',
  nutType: '',
  showStandard: true,
  showImage: true,
  showQr: false,
  qrContent: '',
  widthMm: 37,
  heightMm: 12,
  connectorCategory: '',
  componentCategory: 'Resistor',
  componentMount: 'Through-Hole',
  bearingType: '',
  bearingDetails: '',
  customLine1: '',
  customLine2: '',
  customImageData: '',
  customImageName: '',
};

export const standardFilterState = {
  query: '',
};
