const developmentMessages = [
  "Currently held together with duct tape and optimism.",
  "Under construction because apparently “finished” is too mainstream.",
  "This site runs on caffeine and bad decisions.",
  "Please excuse the chaos — perfection takes forever.",
  "It worked on my machine, so good luck.",
  "Welcome to my bug collection.",
  "Mind the gap between intention and execution.",
  "The dev promised it would be done last week. That was three months ago.",
  "Refreshing might help. Or make it worse. 50/50 chance.",
  "Everything’s temporary — especially this layout.",
  "Currently debugging reality.",
  "We’re professionals. Mostly.",
  "This site is 90% placeholder text and 10% hope.",
  "Expect delays, confusion, and possible emotional damage.",
  "Still in beta, like my life.",
  "Not broken, just expressing itself creatively.",
  "Warning: unpredictable behavior ahead.",
  "Page may load eventually.",
  "It’s not a bug, it’s an undocumented feature.",
  "Design is subjective, code errors are not.",
  "Under construction — again.",
  "The developer is crying somewhere.",
  "Everything is fine. Probably.",
  "This is what “progress” looks like.",
  "Testing in production like a rebel.",
  "Works best on the developer’s computer.",
  "Please stand by while I pretend to know what I’m doing.",
  "Site may contain traces of unfinished code.",
  "If it’s broken, it’s staying that way for now.",
  "Don’t worry, I’ll fix it “later.”",
  "I call this phase “artistic instability.”",
  "The bugs are multiplying faster than I can delete them.",
  "Under active neglect.",
  "Still waiting on divine intervention.",
  "Optimized for maximum confusion.",
  "Sorry for the mess, but not that sorry.",
  "May or may not be haunted.",
  "If you’re reading this, congrats — the site loaded!",
  "Everything is temporary, except this ‘Under Construction’ sign.",
  "Half-baked and fully confident.",
  "The code works… if you don’t touch it.",
  "Enter at your own risk — logic ahead.",
  "Under development, like humanity.",
  "Don’t judge me, it’s a work in regression.",
  "Please hold while I Google how to fix it.",
  "The code runs perfectly… until someone looks at it.",
  "This is fine 🔥.",
  "Caution: programmer trying their best.",
  "Version 0.0.1 and proud.",
  "It’s evolving — just backwards.",
  "Welcome to the construction zone of the internet.",
  "Running on hope and half-finished commits.",
  "If this looks weird, it’s a feature.",
  "Nothing to see here. Literally.",
  "Still under construction since the dawn of time.",
  "Proceed with low expectations.",
  "This site is allergic to stability.",
  "Error 418: Developer is a teapot.",
  "Some features may never exist.",
  "Work in progress. Mostly the “work” part.",
  "Don’t click anything suspicious. Or anything at all.",
  "The CSS is crying in the corner.",
  "Looks better in my dreams.",
  "This is the “temporary forever” version.",
  "I swear I’m fixing it. Tomorrow.",
  "Under construction because I broke it again.",
  "The server is tired too.",
  "Pardon our progress, it’s mostly regress.",
  "This site has commitment issues.",
  "Debug mode is the default mode.",
  "Shhh… the bugs are sleeping.",
  "This was supposed to be simple.",
  "If you think it’s ugly, you should see the code.",
  "Deployed straight from chaos.",
  "Development in progress. Sanity in decline.",
  "The roadmap is just scribbles at this point.",
  "Warning: fragile ego detected.",
  "Currently running on vibes.",
  "Code so fresh it’s still screaming.",
  "Congratulations! You’ve reached the unstable version.",
  "Site may break without warning. Or with plenty of warning.",
  "It’s fine. Everything’s fine. I’m fine.",
  "If you find a bug, name it and keep it.",
  "The backend and frontend are in a toxic relationship.",
  "Built with love, duct tape, and console errors.",
  "Maintenance mode? Nah, chaos mode.",
  "Not perfect, but at least it exists.",
  "Currently in a state of controlled disaster.",
  "Unstable but lovable.",
  "Every refresh is an adventure.",
  "I swear it worked yesterday.",
  "If it loads, celebrate.",
  "My CSS therapist says it’s improving.",
  "You found the test environment. Congrats?",
  "Coming soon… eventually.",
  "The codebase is just a pile of dreams and despair.",
  "Running experiments in disappointment.",
  "Still building. Forever building.",
  "Site is 100% organic chaos.",
  "Under construction until further notice — or burnout.",
];

export function setRandomDevelopmentWarning(element) {
  if (!element) {
    return;
  }

  const randomIndex = Math.floor(Math.random() * developmentMessages.length);
  element.textContent = developmentMessages[randomIndex];
}
